config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#home'
  resources :sessions
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy] do
    resources :challenges
  end

  resources :games
  resources :challenges
  resources :goals

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'

  get '/newmatch', to: 'games#new'
  get '/challenges', to: 'challenges#forum'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/custom_goal_name.rb
class CustomGoalName < ApplicationRecord
  belongs_to :user
  belongs_to :goal
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :custom_goal_names
    accepts_nested_attributes_for :custom_goal_names
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :challenges
    has_many :goals
    validates :username, presence: true, uniqueness: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
    end

    def show
    end

    def update
    end

    def destroy
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def new
    end

    def show
    end

    def update
    end

    def view_history
    end

    def destroy
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    def new
        @goal = Goal.new
    end

    def show
    end

    def update
    end

    def destroy
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    def new
    end

    def show
    end

    def update
    end

    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include ApplicationHelper
    before_action :authorized, only: [:show]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.valid? && @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        @user.username = user_params[:username]

        if user_params[:new_password] != ""
            if @user.authenticate(user_params[:password])
                if user_params[:new_password] == user_params[:password_confirmation]
                    puts "Updating user password..."
                    @user.password = user_params[:new_password]
                    # @user.password_digest = BCrypt::Password.create(user_params[:new_password])
                end
            end
        end

        seed1 = user_params[:pref_short_challenges].to_i
        seed2 = user_params[:pref_long_challenges].to_i << 1
        seed3 = user_params[:pref_topic_challenges].to_i << 2
        seed4 = user_params[:pref_category_challenges].to_i << 3

        new_pref_seed = (seed1 | seed2 | seed3 | seed4).to_i
        if new_pref_seed != @user.pref_seed
            puts "Updating user challenge type preference..."
            @user.pref_seed = new_pref_seed
        end

        @user.icon = user_params[:icon]
        @user.message_color = user_params[:message_color]

        @user.pref_short_challenges = user_params[:pref_short_challenges]
        @user.pref_long_challenges = user_params[:pref_long_challenges]
        @user.pref_topic_challenges = user_params[:pref_topic_challenges]
        @user.pref_category_challenges = user_params[:pref_category_challenges]

        @user.save!
        render :edit
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :new_password, :icon, :message_color, :pref_short_challenges, :pref_long_challenges, :pref_topic_challenges, :pref_category_challenges, :pref_seed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end

    def authorized
        redirect_to login_path unless logged_in?
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
    def load_challenges
        challenges = {
            'Programming' => {
                'Web Development' => {
                    'Backend Web Development' => {
                        
                    },
                    'Frontend Web Development' => {
                        '1' => {
                            'body' => 'Try a new CSS trick you have never used before (short)',
                            'type_seed' => 1010,
                        }
                    },
                },
            },
            'Gardening' => {

            },
        }
    end
end

app/helpers/goals_helper.rb
module GoalsHelper

    def master_goal_list
        {
            'Programming' => {
                'Web Development' => {
                    'Improve web UI/UX design skills' => {
                        'cat_seed' => 00000,
                        'topic_seed' => 00000,
                        'type_seed' => 1110,
                    },
                    'Develop websites more quickly' => {
                        'cat_seed' => 00000,
                        'topic_seed' => 00000,
                        'type_seed' => 0110,
                    },
                    'Learn a new frontend web development framework' => {
                        'cat_seed' => 00000,
                        'topic_seed' => 00010,
                        'type_seed' => 0110,
                    },
                    'Learn about web accessibility standards' => {
                        'cat_seed' => 00000,
                        'topic_seed' => 00020,
                        'type_seed' => 1110,
                    },
                },
                'Mobile App Development' => {
                    'Improve mobile app UI/UX design skills' => {
                        'cat_seed' => 00010,
                        'topic_seed' => 00000,
                        'type_seed' => 1110,
                    },
                    'Develop mobile apps more quickly' => {
                        'cat_seed' => 00010,
                        'topic_seed' => 00000,
                        'type_seed' => 0110,
                    },
                    'Learn a new mobile app development framework' => {
                        'cat_seed' => 00010,
                        'topic_seed' => 00010,
                        'type_seed' => 0110,
                    },
                    'Learn about mobile accessibility standards' => {
                        'cat_seed' => 00010,
                        'topic_seed' => 00020,
                        'type_seed' => 1110,
                    },
                },
            },
            'Gardening' => {

            },
        }
    end
    
    def category_list
        master_goal_list.keys
    end

    def topic_list(category)
        master_goal_list[category].keys()
    end

    def goal_list(category, topic)
        master_goal_list[category][topic].keys()
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<nav id="top-nav">
<%= link_to "Back to Home", root_path %>
<p>Past Challenges</p>
</nav>

<% current_user.challenges.each do |challenge| %>
    <li>
      <a href="<%= challenge_path(challenge) %>">
        <%= challenge.body %>
      </a>
    </li>
<% end %>

<footer>
    <div id="footer-links">
        <div id="footer-aboutlinks">
            <%= link_to "Privacy Policy" %>
            <%= link_to "Cookie Policy" %>
            <%= link_to "How Co-Motivate Works" %>
        </div>

        <div id="footer-sociallinks">
            <%= link_to "LinkedIn" %>
            <%= link_to "DevPost" %>
            <%= link_to "GitHub" %>
        </div>
    </div>

    <div id="footer-copyright">&copy; Avery Gosselin and Stephen Kaplan 2021</div>
</footer>

app/views/games/new.html.erb
<nav id="top-nav">
<%= link_to "Back to Home", root_path %>
<p>New Challenge Setup</p>
</nav>

<% load_challenges %>

<footer>
    <div id="footer-links">
        <div id="footer-aboutlinks">
            <%= link_to "Privacy Policy" %>
            <%= link_to "Cookie Policy" %>
            <%= link_to "How Co-Motivate Works" %>
        </div>

        <div id="footer-sociallinks">
            <%= link_to "LinkedIn" %>
            <%= link_to "DevPost" %>
            <%= link_to "GitHub" %>
        </div>
    </div>

    <div id="footer-copyright">&copy; Avery Gosselin and Stephen Kaplan 2021</div>
</footer>

app/views/goals/new.html.erb
<nav id="top-nav">
<%= link_to "Back", :back %>
<p>Add New Goal</p>
</nav>

<%= form_for @goal do |f| %>

    <section id="goal-pick-category">
        <header>Pick a category:</header>
        <%= select_tag :category_selection, options_for_select(category_list), include_blank: true %>
    </section>

    <section id="goal-pick-topic">
        <header>Pick a topic:</header>
        <%= select_tag :topic_selection, options_for_select(topic_list("Programming")), include_blank: true %>
    </section>

    <section id="goal-pick-goal">
        <header>Pick a goal:</header>
        <%= select_tag :body, options_for_select(goal_list("Programming", "Web Development")), include_blank: true, id: 'goal-selection' %>
    </section>

    <%= f.hidden_field :category_seed, id: 'goal-cat-seed' %>
    <%= f.hidden_field :topic_seed, id: 'goal-topic-seed' %>
    <%= f.hidden_field :type_seed, id: 'goal-type-seed' %>

    <%= f.fields_for :custom_goal_name do |custom_name| %>
        <%= custom_name.label "Add a custom name to this goal" %>
        <%= custom_name.text_field :name %><br>
    <% end %>

    <%= f.submit "Add Goal" %>
<% end %>

<footer>
    <div id="footer-links">
        <div id="footer-aboutlinks">
            <%= link_to "Privacy Policy" %>
            <%= link_to "Cookie Policy" %>
            <%= link_to "How Co-Motivate Works" %>
        </div>

        <div id="footer-sociallinks">
            <%= link_to "LinkedIn" %>
            <%= link_to "DevPost" %>
            <%= link_to "GitHub" %>
        </div>
    </div>

    <div id="footer-copyright">&copy; Avery Gosselin and Stephen Kaplan 2021</div>
</footer>

app/views/users/edit.html.erb
<h1>
    Account Preferences
</h1>

<%= form_for @user do |f| %>
    <section id="settings-username-password">
        <div class="section_content">
            <header>Username and Password</header>
            <%= f.label :username %>
            <%= f.text_field :username, value: current_user.username %><br>

            <div id="change-password-toggle">Change password</div>
            <div id="change-password-form">
                <%= f.label "Current Password" %>
                <%= f.password_field :password %><br>

                <%= f.label :new_password %>
                <%= f.password_field :new_password %><br>

                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %><br>
            </div>
        </div>
    </section>

    <section id="settings-icons-colors">
        <div class="section_content">
            <header>Icons and Colors</header>
            <%= f.label :icon %>
            <%= f.select :icon, ['😀', '😍', '😎', '😜', '👾', '🤖'], value: current_user.icon %><br>

            <%= f.label :message_color %>
            <%= f.select :message_color, ['Red', 'Pink', 'Green', 'Cyan', 'Blue', 'Orange', 'Yellow'], value: current_user.message_color %><br>
        </div>
    </section>

    <section id="settings-goals">
        <div class="section_content">
            <header>Goals</header>
            <% current_user.goals.each do |goal| %>
                <li>
                <a href="<%= goal_path(challenge) %>">
                    <%= goal.body %>
                </a>
                </li>
            <% end %>
            <%= link_to "Add Goal", new_goal_path %>
        </div>
    </section>

    <section id="settings-challenge-prefs">
        <div class="section_content">
            <header>Challenge Type Preference</header>

            <%= f.label "Short (~15 minute) Challenges" %>
            <%= f.check_box :pref_short_challenges, value: current_user.pref_short_challenges %><br>

            <%= f.label "Long (1+ hour) Challenges" %>
            <%= f.check_box :pref_long_challenges, value: current_user.pref_long_challenges %><br>

            <%= f.label "Topic-Focused Challenges" %>
            <%= f.check_box :pref_topic_challenges, value: current_user.pref_topic_challenges %><br>

            <%= f.label "Category-Focused Challenges" %>
            <%= f.check_box :pref_category_challenges, value: current_user.pref_category_challenges %><br>
        </div>
    </section>

    <div class="buttons">
        <%= f.submit "Save Changes", class: "button" %>
        <%= link_to "Back to Home", root_path, class: "button-small" %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>New Users Page</h1>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %><br>

    <%= f.submit "Create Account" %>
<% end %>